name: shiny-happiness
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - rdkit
  - networkx
  - tqdm
  - h5py
  - pytorch=1.12.0
  - pytorch-lightning=1.7.7
  - pip:
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - torch-geometric
    - selfies
    - torchmetrics==0.11.4
    - pydantic
    - molecule-generation
